name: Build and Publish to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Log-IN to AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
            aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t app:v1 .
          docker tag app:v1 mcsolkeens/app_dev
          docker push mcsolkeens/app_dev

