name: Build and Publish to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Log-IN to AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
            aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR 
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_SECRET_ACCESS }}
        env:
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Build Docker Image
        run: |
          docker build -t app2ecr:lastest .
          docker tag app2ecr:lastest public.ecr.aws/j6x6c3z0/app2ecr:latest
          docker push public.ecr.aws/j6x6c3z0/app2ecr:latest

