name: Build and Publish to AWS ECR

on:
  push:
    branches:
      - main

jobs:
   build-and-push:
     name: Build and Push Docker Image to ECR
     runs-on: ubuntu-latest

     steps:
      - name: Code Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Log-IN to AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          aws-region: ${{ secrets.AWS_REGION }}
            
   build-and-push-ecr-public:
     name: push to ecr registry
     runs-on: ubuntu-latest
     needs: 
        build-and-push
     steps:
      - name: Code Checkout 
        uses: actions/checkout@v4.2.2
        
      - name: Login to AWS ECR 
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_SECRET_ACCESS }}
        env:
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Build Docker Image
        run: |
          docker build -t app2ecr:latest .
          docker tag app2ecr:latest public.ecr.aws/j6x6c3z0/app2ecr:latest
          docker push public.ecr.aws/j6x6c3z0/app2ecr:latest

   build-and-push-ecr-private:
     name: push to ecr registry-private
     runs-on: ubuntu-latest
     needs: 
      build-and-push-ecr-public
     steps:
      - name: Code Checkout 
        uses: actions/checkout@v4.2.2
        
      - name: Login to AWS ECR 
        uses: docker/login-action@v3
        with:
          registry: 043309324225.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY }}
          password: ${{ secrets.AWS_SECRET_ACCESS }}
        env:
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Build Docker Image
        run: |
          docker build -t app2ecr:latest .
          docker tag app2ecr:latest 043309324225.dkr.ecr.us-east-1.amazonaws.com/app2ecr:latest
          docker push 043309324225.dkr.ecr.us-east-1.amazonaws.com/app2ecr:latest
